import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";

const global = Nunito_Sans({
	subsets: ["latin"],
});

import "./globals.css";

import Header from "./_components/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' className="dark:bg-dark-darker">
			<body className={`${global.className}`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
